service: ProductsAPI
	
frameworkVersion: "3.10.2" # Lock Serverless version

plugins:
  - serverless-deployment-bucket # Defines name and configuration for the deployment bucket
  - serverless-certificate-creator # Creates certificate, if needed
  - serverless-domain-manager # Defines Route53 Domain
  - serverless-python-requirements # Installs Python requirements
  - serverless-iam-roles-per-function # Allows IAM roles per function
  - serverless-prune-plugin # Deletes older versions

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage}
  region: eu-west-3 #${opt:region, "eu-west-3"}

  # Bucket that will store the zipped API
  deploymentBucket:
    name: ${self:custom.bucket.bucketName}
    serverSideEncryption: ${self:custom.bucket.serverSideEncryption}
  
  # APi Gateway configuration
  apiGateway:
    #shouldStartNameWithService: true
    apiKeys:
      - ${opt:stage}-${self:service}-key
    apiKeySourceType: HEADER

  tracing:
    apiGateway: true
    lambda: true
 
custom:
  # Common configuration
  bucket: ${file(../serverless-settings/buckets.yml):${self:provider.stage}}
  domain: ${file(../serverless-settings/domains.yml):${self:provider.stage}}
  prune: ${file(../serverless-settings/prune.yml):${self:provider.stage}}

  # S3
  deploymentBucket: ${self:custom.bucket.bucketConfiguration}

  # Amazon Certificate Manager
  customCertificate:
    hostedZoneNames: ${self:custom.domain.certificate.hostedZoneNames} # don't forget the dot on the end - is required by Route53
    certificateName: ${self:custom.domain.certificate.certificateName}
    region: ${self:provider.region}

  # Route53
  customDomain:
    domainName: ${self:custom.domain.domainName}
    certificateName: ${self:custom.domain.certificate.certificateName}
    createRoute53Record: true # Enable plugin to create an A Alias and AAAA Alias records in Route53
    autoDomain: false # Enable plugin to autorun create_domain/delete_domain as part of sls deploy/remove
    basePath: "products" # API base path
    endpointType: "regional"

  # Require or not API keys when accessing endpoints
  apiKeyOnlyAccess:
    development: true
    production: true


package:
  individually: true
  exclude:
    - "**"

functions:
  createProduct:
    name: ${self:provider.stage}-${self:service}-create-product
    description: Responsible for creating new products
    runtime: python3.9
    timeout: 10
    package:
      include:
        - ../common/exceptions.py
        - ../common/api.py
        - ../common/enums.py
        - ../common/transformers/**.py
        - ../common/utilities.py
        - products_table.py
        - create_product.py
    handler: create_product.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          # - dynamodb:Query
          # - dynamodb:Scan
          # - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          Fn::GetAtt:
            - ProductsTable
            - Arn
    environment:
      PRODUCTS_TABLE_NAME:
        Ref: ProductsTable
    events:
      - http:
          path: /create-product
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          private: ${self:custom.apiKeyOnlyAccess.${self:provider.stage}}

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH

  # Outputs:
    # CreateUserLambdaArn:
    #   Description: "${self:service} lambda Arn"
    #   Value:
    #     Fn::GetAtt: ServiceLambdaFunction.Arn
    #   Export:
    #     Name: MyServiceARN

