service: CommonLayer

frameworkVersion: "3.19.0" # Lock Serverless version

plugins:
  - serverless-deployment-bucket # Defines name and configuration for the deployment bucket

provider:
  name: aws
  runtime: python3.9
  stage: ${env:ENVIRONMENT}
  region: eu-west-3

  deploymentBucket:
    name: ${self:custom.bucket.bucketName}

custom:
  # Common configuration
  bucket: ${file(../serverless_settings/buckets.yml):${self:provider.stage}}
  deploymentBucket: ${self:custom.bucket.bucketConfiguration}

package:
  individually: true

layers:
  common:
    path: .
    name: ${self:provider.stage}-${self:service}
    description: "Custom common functionality to be shared across lambdas within the organization"
    compatibleRuntimes:
      - python3.9
    licenseInfo: MIT License
    retain: false

resources:
  Resources:
    commonLayerArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:provider.stage}/layers/${self:service}
        Type: String
        Value: !Ref CommonLambdaLayer
