name: Deploy API with Serverless

on: 
  workflow_dispatch:
    inputs:
      apiToDeploy:
        description: "API to deploy (folder name)"   
        required: true
        default: "users-manager-api"

jobs:
  deploy:
    name: Run tests & deploy with Serverless
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Install Serverless
        run: npm install -g serverless@3.10.2

      - name: Setup Serverless
        run: |
          sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          serverless plugin install --name serverless-domain-manager
          serverless plugin install --name serverless-python-requirements
          serverless plugin install --name serverless-iam-roles-per-function
          serverless plugin install --name serverless-prune-plugin

      - name: Serverless deploy
        working-directory: ${{ github.event.inputs.apiToDeploy }}
        run: sls deploy --stage ${{ env.ENVIRONMENT }}

